name: test c

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./c
    steps:
      - uses: actions/checkout@v3

      - name: Install CUnit
        run: sudo apt-get install libcunit1 libcunit1-doc libcunit1-dev

      - name: Install xsltprox
        run: sudo apt-get install xsltproc

      - name: Compile fibonacci
        run: make fibonacci

      - name: Run fibonacci script 
        run: ./fibonacci 30

      - name: Compile and run tests
        run: make test

      - name: Convert XML report into XML xUnit
        run: |
          make xunit-report
          cat TestResults.xml

      - name: Clean up
        run: make clean
