name: test c

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Compile fibonacci
        run: |
          cd c/
          make fibonacci

      - name: Run fibonacci script 
        run: |
          cd c/
          ./fibonacci 30

      - name: Compile and run tests
        run: |
          cd c/
          make test

      - name: Convert XML report into XML xUnit
        run: |
          cd c/
          make xunit-report
          cat TestResults.xml

      - name: Clean up
        run: |
          cd c/
          make clean
