name: test php

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: phpunit

      - name: Run fibonacci script 
        run: php php/src/FibonacciProgram.php 30

      - name: Test fibonacci script
        run: |
          phpunit --log-junit TestResults.xml --bootstrap php/src/autoload.php php/test/FibonacciTest.php
          cat TestResults.xml
