name: test python

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: run python script
      - run: python python/maths/fibonacci.py 30

      - name: test python script
      - run: py.test --junit-xml=report.xml
      - run: cat report.xml
