name: test python

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: pytest
      - run: python python/maths/fibonacci.py 30
      - run: py.test --junit-xml=report.xml
      - run: cat report.xml
